### ISSUE TITLE
Z Axis 

### ISSUE THREAD

**Issue by jvegaf** [jand1122/RepRap-XY#1]
Hi, first of all, congratulations for you awesome work !!!!

I'm thinking fork you repo and do a few changes

do you know what will happens I try change 12 mm smooth bar by a 8mm smooth bar on Z Axis ?

(I have a 2  8mm smooth bar prepared for Z axis)

Thanks

**Comment by jand1122** [comment]
Hi Jose,

Thanks, for the compliment. I think it is not really difficult to change it
to 8mm rods for the Z-axis, but I think it is not a good idea. the 12mm
rods are much stiffer than 8 mm rods. I think you will get to much flex in
the bed. I would recommend to get some 12 mm rods.

Best regards,

Jan

2015-01-19 3:23 GMT+01:00 Jose Vega <notifications@github.com>:
