### ISSUE TITLE
Printer belt construction

### ISSUE THREAD

**Issue by dragondgold** [jand1122/RepRap-XY#5]
Hi! I'm starting to build this printer and I'm having some problems to put the belts. I have read the forum but couldn't find a clear diagram about how to put the belts and how the tension system works. Would you mind taking a picture inside where the motors are mounted?

**Comment by g2david** [comment]
There exists an adjustable bearing next to the motor mount

**Comment by dragondgold** [comment]
@g2david yes, I can see it. But how do you put the belts inside? I can't find any diagram or image and I can't tell from your pictures what bearings, pulley and spacers to put inside

![Image](http://i.imgur.com/xHRNZMz.jpg)

**Comment by g2david** [comment]
Let me t
![20151022234152](https://cloud.githubusercontent.com/assets/12928787/10686192/428cf3c0-7994-11e5-8308-1b6ae41b9075.jpg)

![20151022234138](https://cloud.githubusercontent.com/assets/12928787/10686200/4b5494ea-7994-11e5-952f-892d79af9a9a.jpg)

![20151022234052](https://cloud.githubusercontent.com/assets/12928787/10686206/4ff0af52-7994-11e5-8914-1397cd8cd6f1.jpg)
![20151022234102](https://cloud.githubusercontent.com/assets/12928787/10686208/531eb5c0-7994-11e5-90f7-940407b24a75.jpg)

**Comment by g2david** [comment]
![20151023001548](https://cloud.githubusercontent.com/assets/12928787/10686676/07494e76-7999-11e5-965d-056031a8f1f6.jpg)

**Comment by g2david** [comment]
If you start with the X Carriage, It is quite easy to pass through

Otherwise, You need to have patient to fish the belt inside the XY blocks. It takes me 30 mins. I use a dummy belt to fish the belt out of the blocks.  Sweating

**Comment by dragondgold** [comment]
Thank you very much! Great printer btw :) I also found a great assembly in the files `RepRap-XY.step`
