### ISSUE TITLE
How do these belt clips hold? They seem not to have perpendicular traction on the belts.

### ISSUE THREAD

**Issue by brunobasto** [jand1122/RepRap-XY#7]
Congrats on the project! I've seen the videos. It looks awesome!

**Comment by jand1122** [comment]
Both clips on the right side are with the open side up, so the traction is at the front, the smooth side at the back. At the left side the open side is down, so the traction is also at the front and the smooth side at the back

Just slide the belt from the open side into the clip. (Single, do not fold the beld) You have to cut the belts to length within a few teeth accurate. Tensioning is done in the motor blocks. It is strong enough. it has never failed in over a yesr of printing many kg of ABS plastic.

**Comment by brunobasto** [comment]
Awesome! Good to know.

Thank you
